# Generated by Django 2.1 on 2019-08-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190802_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.CharField(max_length=200)),
                ('quarterly', models.CharField(max_length=200)),
                ('halfyearly', models.CharField(max_length=200)),
                ('annual', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Subscription_type'),
        ),
    ]
