# Generated by Django 2.1 on 2019-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190803_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcription_type_quarterly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterly', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_type_annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_type_halfyearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halfyearly', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_type_monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='sub_type',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscription_type',
        ),
    ]
