# Generated by Django 2.1 on 2019-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190807_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
    ]
